name: untitled
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter_session_manager: ^1.0.3
  image_picker: ^0.8.6
  shared_preferences: ^2.0.8
  
  rounded_loading_button: ^2.0.8
  flutter_hooks: ^0.18.5+1
  no_context_navigation: ^2.1.2
  carousel_slider: ^4.0.0
  flutter_login: ^4.0.0
  animated_button: ^0.2.0
  url_launcher: ^6.1.7
  hexcolor: ^2.0.7
  any_animated_button: ^0.0.3
  syncfusion_flutter_pdfviewer: ^20.4.41
  flutter_carousel_slider: ^1.0.8
  filter_list: ^0.0.8
  mvc_pattern: ^8.12.0
  flutter_swiper_plus : ^2.0.4
  image_utils_class: ^2.0.0
  flutter_email_sender: ^5.0.2
  flutter:
   
    sdk: flutter
  
  http: 0.13.3
  flutter_calendar_carousel:
  table_calendar: ^2.2.1
  flutter_local_notifications: ^9.6.0
  timezone: ^0.8.0
  rxdart: ^0.27.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^0.22.0
  async: ^2.8.2
  highlight_text: ^1.6.0
  avatar_glow: ^2.0.2
  speech_to_text: ^6.1.0
  google_place: ^0.4.7
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.2.2
  dio: ^4.0.6
  geolocator: ^9.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  modal_progress_hud_nsn: ^0.3.0
  firebase_storage: ^11.0.10
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  json_to_model: ^3.0.1
  quiver: ^3.0.1+1
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
 
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - C:/Users/MIX-IT/Desktop/images/fish fillet1.jpg
    - assets/images/logo.png
    - assets/icons/
    - assets/images/
    - C:/Users/MIX-IT/Desktop/images/fish fillet1.jpg
    - C:/Users/MIX-IT/Desktop/images/fish fillet2.jpg
    - C:/Users/MIX-IT/Desktop/images/flour1.jpg
    - C:/Users/MIX-IT/Desktop/images/flour2.jpg
    - C:/Users/MIX-IT/Desktop/images/French dressing1.jpg
    - C:/Users/MIX-IT/Desktop/images/French dressing2.jpg
    - C:/Users/MIX-IT/Desktop/images/garlic bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/garlic bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/homemade cheese1.jpg
    - C:/Users/MIX-IT/Desktop/images/homemade cheese2.jpg
    - C:/Users/MIX-IT/Desktop/images/icre flakes1.jpg
    - C:/Users/MIX-IT/Desktop/images/barley1.jpg
    - C:/Users/MIX-IT/Desktop/images/barley2.jpg
    - C:/Users/MIX-IT/Desktop/images/barley3.jpg
    - C:/Users/MIX-IT/Desktop/images/biscuit1.jpg
    - C:/Users/MIX-IT/Desktop/images/biscuit2.jpg
    - C:/Users/MIX-IT/Desktop/images/bread roll1.jpg
    - C:/Users/MIX-IT/Desktop/images/bread roll2.jpg
    - C:/Users/MIX-IT/Desktop/images/bread roll3.jpg
    - C:/Users/MIX-IT/Desktop/images/bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/buckwheat1.jpg
    - C:/Users/MIX-IT/Desktop/images/buckwheat2.jpg
    - C:/Users/MIX-IT/Desktop/images/buckwheat3.jpg
    - C:/Users/MIX-IT/Desktop/images/buns1.jpg
    - C:/Users/MIX-IT/Desktop/images/butter1.jpg
    - C:/Users/MIX-IT/Desktop/images/butter2.jpg
    - C:/Users/MIX-IT/Desktop/images/buttermilk1.jpg
    - C:/Users/MIX-IT/Desktop/images/buttermilk2.jpg  

    - C:/Users/MIX-IT/Desktop/images/cake mix1.jpg
    - C:/Users/MIX-IT/Desktop/images/cake mix2.jpg
    - C:/Users/MIX-IT/Desktop/images/cakes1.jpg
    - C:/Users/MIX-IT/Desktop/images/cakes2.jpg
    - C:/Users/MIX-IT/Desktop/images/cakes3.jpg
    - C:/Users/MIX-IT/Desktop/images/cereal1.jpg
    - C:/Users/MIX-IT/Desktop/images/cereal2.jpg
    - C:/Users/MIX-IT/Desktop/images/cereal3.jpg
    - C:/Users/MIX-IT/Desktop/images/Cheddar1.jpg
    - C:/Users/MIX-IT/Desktop/images/Cheddar2.jpg
    - C:/Users/MIX-IT/Desktop/images/cheese1.jpg
    - C:/Users/MIX-IT/Desktop/images/cheese2.jpg
    - C:/Users/MIX-IT/Desktop/images/cinnamon roll1.jpg
    - C:/Users/MIX-IT/Desktop/images/cinnamon roll2.jpg
    - C:/Users/MIX-IT/Desktop/images/condensed milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/condensed milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/cookie1.jpg
    - C:/Users/MIX-IT/Desktop/images/cookie2.jpg
    - C:/Users/MIX-IT/Desktop/images/cookies1.jpg
    - C:/Users/MIX-IT/Desktop/images/cookies2.jpg
    - C:/Users/MIX-IT/Desktop/images/cookies3.jpg
    - C:/Users/MIX-IT/Desktop/images/corn bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/corn bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/corn flake1.jpg
    - C:/Users/MIX-IT/Desktop/images/corn flake2.jpg
    - C:/Users/MIX-IT/Desktop/images/corn flake3.jpg
     
    - C:/Users/MIX-IT/Desktop/images/corn oil1.jpg
    - C:/Users/MIX-IT/Desktop/images/corn oil2.jpg
    - C:/Users/MIX-IT/Desktop/images/corn1.jpg
    - C:/Users/MIX-IT/Desktop/images/corn2.jpg
    - C:/Users/MIX-IT/Desktop/images/corn3.jpg
    - C:/Users/MIX-IT/Desktop/images/crab1.jpg
    - C:/Users/MIX-IT/Desktop/images/crab2.jpg
    - C:/Users/MIX-IT/Desktop/images/cracker1.jpg
    - C:/Users/MIX-IT/Desktop/images/cracker2.jpg
    - C:/Users/MIX-IT/Desktop/images/cream cheese1.jpg
    - C:/Users/MIX-IT/Desktop/images/cream cheese2.jpg
    - C:/Users/MIX-IT/Desktop/images/cream1.jpg
    - C:/Users/MIX-IT/Desktop/images/cream2.jpg
    - C:/Users/MIX-IT/Desktop/images/dough1.jpg
    - C:/Users/MIX-IT/Desktop/images/dough2.jpg
    - C:/Users/MIX-IT/Desktop/images/dry milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/dry milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/dry milk3.jpg
    - C:/Users/MIX-IT/Desktop/images/dumplings1.jpg
    - C:/Users/MIX-IT/Desktop/images/dumplings2.jpg
    - C:/Users/MIX-IT/Desktop/images/fish fillet1.jpg
    - C:/Users/MIX-IT/Desktop/images/fish fillet2.jpg
    - C:/Users/MIX-IT/Desktop/images/flour1.jpg
    - C:/Users/MIX-IT/Desktop/images/flour2.jpg
    - C:/Users/MIX-IT/Desktop/images/French dressing1.jpg
    - C:/Users/MIX-IT/Desktop/images/French dressing2.jpg

    - C:/Users/MIX-IT/Desktop/images/garlic bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/garlic bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/homemade cheese1.jpg
    - C:/Users/MIX-IT/Desktop/images/homemade cheese2.jpg
    - C:/Users/MIX-IT/Desktop/images/icre flakes1.jpg
    - C:/Users/MIX-IT/Desktop/images/icre flakes2.jpg
    - C:/Users/MIX-IT/Desktop/images/icre flakes3.jpg
    - C:/Users/MIX-IT/Desktop/images/Italian dressing1.jpg
    - C:/Users/MIX-IT/Desktop/images/Italian dressing2.jpg
    - C:/Users/MIX-IT/Desktop/images/low-fat milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/low-fat milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/macaroni1.jpg
    - C:/Users/MIX-IT/Desktop/images/macaroni2.jpg
    - C:/Users/MIX-IT/Desktop/images/milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/moked fish1.jpg
    - C:/Users/MIX-IT/Desktop/images/moked fish2.jpg
    - C:/Users/MIX-IT/Desktop/images/Mozzarella1.jpg
    - C:/Users/MIX-IT/Desktop/images/Mozzarella2.jpg
    - C:/Users/MIX-IT/Desktop/images/muesli1.jpg
    - C:/Users/MIX-IT/Desktop/images/muesli2.jpg
    - C:/Users/MIX-IT/Desktop/images/muesli3.jpg
    - C:/Users/MIX-IT/Desktop/images/nonfat milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/nonfat milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/noodles1.jpg
    - C:/Users/MIX-IT/Desktop/images/noodles2.jpg

    - C:/Users/MIX-IT/Desktop/images/oats1.jpg
    - C:/Users/MIX-IT/Desktop/images/oats2.jpg
    - C:/Users/MIX-IT/Desktop/images/oats3.jpg
    - C:/Users/MIX-IT/Desktop/images/oats4.jpg
    - C:/Users/MIX-IT/Desktop/images/olive oil1.jpg
    - C:/Users/MIX-IT/Desktop/images/olive oil2.jpg
    - C:/Users/MIX-IT/Desktop/images/Parmesan1.jpg
    - C:/Users/MIX-IT/Desktop/images/Parmesan2.jpg
    - C:/Users/MIX-IT/Desktop/images/pasta1.jpg
    - C:/Users/MIX-IT/Desktop/images/pasta2.jpg
    - C:/Users/MIX-IT/Desktop/images/pasteurized milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/pasteurized milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/pies1.jpg
    - C:/Users/MIX-IT/Desktop/images/pies2.jpg
    - C:/Users/MIX-IT/Desktop/images/pies3.jpg
    - C:/Users/MIX-IT/Desktop/images/popcorn1.jpg
    - C:/Users/MIX-IT/Desktop/images/popcorn2.jpg
    - C:/Users/MIX-IT/Desktop/images/popcorn3.jpg
    - C:/Users/MIX-IT/Desktop/images/poppy seed roll1.jpg
    - C:/Users/MIX-IT/Desktop/images/poppy seed roll2.jpg
    - C:/Users/MIX-IT/Desktop/images/raisin bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/raisin bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/ravioli1.jpg
    - C:/Users/MIX-IT/Desktop/images/ravioli2.jpg
    - C:/Users/MIX-IT/Desktop/images/rice1.jpg
    - C:/Users/MIX-IT/Desktop/images/rice2.jpg

    - C:/Users/MIX-IT/Desktop/images/rice3.jpg
    - C:/Users/MIX-IT/Desktop/images/rolls.jpg
    - C:/Users/MIX-IT/Desktop/images/Russian dressing1.jpg
    - C:/Users/MIX-IT/Desktop/images/Russian dressing2.jpg
    - C:/Users/MIX-IT/Desktop/images/rye bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/rye bread2.jpg
   
    - C:/Users/MIX-IT/Desktop/images/rye2.jpg
    - C:/Users/MIX-IT/Desktop/images/rye3.jpg
    - C:/Users/MIX-IT/Desktop/images/salad dressing1.jpg
    - C:/Users/MIX-IT/Desktop/images/salad dressing2.jpg
    - C:/Users/MIX-IT/Desktop/images/salmon steak1.jpg
    - C:/Users/MIX-IT/Desktop/images/salmon steak2.jpg
    - C:/Users/MIX-IT/Desktop/images/salted fish1.jpg
    - C:/Users/MIX-IT/Desktop/images/salted fish2.jpg
    - C:/Users/MIX-IT/Desktop/images/seafood1.jpg
    - C:/Users/MIX-IT/Desktop/images/seafood2.jpg
    - C:/Users/MIX-IT/Desktop/images/sesame oil1.jpg
    - C:/Users/MIX-IT/Desktop/images/poppy seed roll1.jpg
    - C:/Users/MIX-IT/Desktop/images/sesame oil2.jpg
    - C:/Users/MIX-IT/Desktop/images/sesame roll1.jpg
    - C:/Users/MIX-IT/Desktop/images/sesame roll2.jpg
    - C:/Users/MIX-IT/Desktop/images/sour cream1.jpg
    - C:/Users/MIX-IT/Desktop/images/sour cream2.jpg
    - C:/Users/MIX-IT/Desktop/images/sour milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/sour milk2.jpg

    - C:/Users/MIX-IT/Desktop/images/sourdough bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/sourdough bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/spaghetti1.jpg
    - C:/Users/MIX-IT/Desktop/images/spaghetti2.jpg
    - C:/Users/MIX-IT/Desktop/images/squid1.jpg
    - C:/Users/MIX-IT/Desktop/images/squid2.jpg
    - C:/Users/MIX-IT/Desktop/images/sunflower seed oil1.jpg
    - C:/Users/MIX-IT/Desktop/images/sunflower seed oil2.jpg
    - C:/Users/MIX-IT/Desktop/images/toast1.jpg
    - C:/Users/MIX-IT/Desktop/images/toast2.jpg
    - C:/Users/MIX-IT/Desktop/images/tortilla1.jpg
    - C:/Users/MIX-IT/Desktop/images/tortilla2.jpg
    - C:/Users/MIX-IT/Desktop/images/vegetable oil1.jpg
    - C:/Users/MIX-IT/Desktop/images/vegetable oil2.jpg
    - C:/Users/MIX-IT/Desktop/images/vermicelli1.jpg
    - C:/Users/MIX-IT/Desktop/images/vermicelli2.jpg
    - C:/Users/MIX-IT/Desktop/images/wafer1.jpg
    - C:/Users/MIX-IT/Desktop/images/wafer2.jpg
    - C:/Users/MIX-IT/Desktop/images/waffle1.jpg
    - C:/Users/MIX-IT/Desktop/images/waffle2.jpg
    - C:/Users/MIX-IT/Desktop/images/wheat.jpg
    - C:/Users/MIX-IT/Desktop/images/white bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/white bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/whole milk1.jpg
    - C:/Users/MIX-IT/Desktop/images/whole milk2.jpg
    - C:/Users/MIX-IT/Desktop/images/whole-wheat bread1.jpg
    - C:/Users/MIX-IT/Desktop/images/whole-wheat bread2.jpg
    - C:/Users/MIX-IT/Desktop/images/yogurt2.jpg
    - C:/Users/MIX-IT/Desktop/images/yogurt1.jpg
    




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages